### PR TITLE
Support react 17 peer dep

### PR DESCRIPTION
**Pull request by bcomnes**
Geting peer dep warnings.  Everything still works though.

### CODE REVIEW

**Comment by mtmacdonald** [comment]
Also requesting for this to be merged please!

**Comment by Hypnosphi** [comment]
@jamiebuilds can you please review

**Comment by sfcgeorge** [comment]
Since this is a polyfill it seems loosening the dependency to >= React 14 would be better. Even if React removes `createContext` again in a future version the polyfill would just start working again. 

Currently with this overly strict dependency downstream projects like [Reach Router](https://github.com/reach/router/pull/432#issuecomment-734891630) (which uses create-react-context) and [Storybook](https://github.com/storybookjs/storybook/issues/12983) (which uses Reach) are failing to install using NPM v7 due to it now [handling peerDependencies correctly](https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major).

**Comment by haysclark** [comment]
> Since this is a polyfill it seems loosening the dependency to >= React 14 would be better. Even if React removes `createContext` again in a future version the polyfill would just start working again.

I believe that there is [some wisdom behind being explicit](https://martinfowler.com/ieeeSoftware/explicit.pdf), especially when it comes to JS dependencies (in this case "peerDependencies"); but I do agree it's rather subjective. 😉 My take-away from the [React 17 release notes](https://es.reactjs.org/blog/2020/10/20/react-v17.html) is that Facebook is preparing the community for API _breaking changes_ coming in future versions of React. Knowing that future versions of React are not guaranteed to be backwards compatible, makes me lean away from the allure of `>= React 14`.

Just [my two cents](https://en.wikipedia.org/wiki/My_two_cents). ¯\\_(ツ)_/¯

**Comment by haysclark** [comment]
> > Since this is a polyfill it seems loosening the dependency to >= React 14 would be better. Even if React removes `createContext` again in a future version the polyfill would just start working again.
> 
> My take-away from the [React 17 release notes](https://es.reactjs.org/blog/2020/10/20/react-v17.html) is that Facebook is preparing the community for API _breaking changes_ coming in future versions of React. Knowing that future versions of React are not guaranteed to be backwards compatible, makes me lean away from the allure of `>= React 14`.

@sfcgeorge Actually, I think you **are correct** that `>= React 14` would be better for this particular repo. The fact that this library **is** a `polyfill` completely changes my feeling towards its future compatibility and maintenance. It just took me a little time to catch up with your insight. :) TLDR; Re-reading your comment above, as well as your feedback in [reach/router](https://github.com/reach/router/pull/432#issuecomment-734891630) helped me understand your perspective. 👏

**Comment by bcomnes** [comment]
All good points, just going with what will make things work, and the existing pattern, though changing it to > 14 would be better.

**Comment by haysclark** [comment]
@jamiebuilds Merge? Feedback? 😄

**Comment by sfcgeorge** [comment]
Thanks @haysclark, there's good arguments both ways. @bcomnes is right, keeping most things the same is the easiest way to get something merged, and "done is better than perfect" ☺️

**Comment by haysclark** [comment]
still waiting for @jamiebuilds

**Comment by revmischa** [comment]
Please, I beg of you, merge this!
It breaks storybook with react 17 if you use npm v7, which catches these broken peer deps

```
Could not resolve dependency:
peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from create-react-context@0.3.0
node_modules/@reach/router/node_modules/create-react-context
  create-react-context@"0.3.0" from @reach/router@1.3.4
  node_modules/@reach/router
    @reach/router@"^1.3.3" from @storybook/api@6.1.11
```

**Comment by bcomnes** [comment]
I reached out to Jamie on Twitter a while back but did not receive a response.  Would anyone be willing to launch and maintain a maintenance fork of this dependency and attempt to land it downstream to reach/storybook ?

**Comment by Hypnosphi** [comment]
I think I can

**Comment by Hypnosphi** [comment]
Forked to https://github.com/Hypnosphi/create-react-context & published as `@hypnosphi/create-react-context`

I used `>= 0.14.0` per suggestion by @sfcgeorge

**Comment by bcomnes** [comment]
I am no longer interested in maintaining this pull request.  If anyone wants to offer up another one here, feel free.  I will be switching to @Hypnosphi's fork.

**Pull request closed without merging**
