### PR TITLE
Remove redundant default value

### PR DESCRIPTION
**Pull request by donavon**
It’s done in `index.js`.

### CODE REVIEW

**Comment by jrylan** [comment]
I don't think it's redundant. If a library were using `create-react-context` but the top level project was using React > 16, then this line would allow the built-in React.createContext to be used and fall back to createReactContext.

**Comment by donavon** [comment]
Isn't that what this line does? (i.e. you're doing it twice)

https://github.com/jamiebuilds/create-react-context/blob/master/src/index.js#L5

**Comment by jrylan** [comment]
@donavon aha! You are correct there. Sorry I missed that. Your change has my vote.... but I'm just an outsider and my vote doesn't count here.

**Comment by timwangdev** [comment]
Could we make a release for this? We are kind relied on the pure implementation.

**Pull request merged**
